esphome:
  name: cam1
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "SSID"
  password: "Password"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.XXX.XXX
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.XXX.XXX
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "Camera Password"

ota:
  password: "Camera Password"


esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  vertical_flip: true
  brightness: 0
  

  # Image settings
  name: cam1
